-- TABLE CREATION
CREATE TABLE STUDENT(
ROLL_NO INT PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
JOINING_DATE DATE,
ADDRESS VARCHAR(255)
);


-- DATA INSERTION:

-- INSERTING 1 ROW AT A time
INSERT INTO STUDENT VALUES(01,'RAM' , '2000-12-20' , 'DELHI');
INSERT INTO STUDENT VALUES(02,'SHYAM' , '2001-06-01' , 'MUMBAI');

-- INSERTING MULTIPLE ROWS AT A TIME 
INSERT INTO STUDENT(ROLL_NO, NAME, JOINING_DATE, ADDRESS) VALUES
(03,'GUPTA' , '2020-01-28' , 'PUNE'),
(04,'RAMAN' , '2010-03-05' , 'BANGLURU'),
(05,'NITISH' , '2005-05-10' , 'SILIGURI');






-- DATA RETRIEVAL
SELECT * FROM STUDENT;


